import "~/main.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { cn } from "~/lib/utils";
import { CookiesProvider } from "next-client-cookies/server";
import type { ReactNode } from "react";
import { getTranslation } from "~/app/i18n/server";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

async function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  const { i18n } = await getTranslation();

  return (
    <CookiesProvider>
      <html lang={i18n.language} className={cn(`${geist.variable}`, "dark")}>
        <body>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </body>
      </html>
    </CookiesProvider>
  );
}

export default RootLayout;
